theme = "hugo-book"

[params]
BookTheme = "auto"
BookToC = true

# Show previous/next navigation links
BookNextPrev = true

BookSearch = true
BookMenuBundle = "/menu"

BookRepo = "https://github.com/aminbenmansour/google-sre-book-summary"

# Edit page links
BookEditPath = "edit/main"

# Show last modified date
BookDateFormat = "January 2, 2006"

# Enable portable links between pages
BookPortableLinks = true
